### ISSUE TITLE
Slackrtm crash and sync pictures error

### ISSUE THREAD

**Issue by cd334** [errror/hangupsbot#6]
Hello!

Today our slackrtm hangout integration is crashed. Then we restared the hangoutsbot, and the picture sync from slack to HO not workink any more.

Here are our error logs
1. crash:
 08:20:01 INFO root: Connection lost!
08:21:31 ERROR hangups.channel: Ran out of retries for long-polling request
08:21:31 INFO root: bot is exiting
08:21:31 INFO plugins: commands.permamem unloaded
08:21:31 INFO plugins: plugins.image_links unloaded
08:21:31 INFO plugins: plugins.syncrooms unloaded
08:21:31 INFO plugins: plugins.default unloaded
08:21:31 INFO plugins: commands.basic unloaded
08:21:31 INFO plugins: plugins.botaliases unloaded
08:21:31 INFO plugins: monkeypatch.otr_support unloaded
08:21:31 INFO plugins: plugins.dnd unloaded
08:21:31 INFO plugins: plugins.syncrooms_autotranslate unloaded
08:21:31 INFO plugins: plugins.convtools unloaded
08:21:31 INFO plugins: commands.loggertochat unloaded
08:21:31 INFO plugins: commands.tagging unloaded
08:21:31 INFO plugins: plugins.starter unloaded
08:21:31 INFO plugins: commands.plugincontrol unloaded
08:21:31 INFO plugins: plugins.syncrooms_config unloaded
08:21:31 INFO plugins: plugins.slackrtm unloaded
08:21:31 INFO plugins: plugins.namelock unloaded
08:21:31 INFO plugins: commands.convid unloaded
Traceback (most recent call last):
  File "/home/cd334/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 1115, in _handle_slackout
    slackrtm.handle_ho_message(event)
  File "/home/cd334/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 964, in handle_ho_message
    icon_url=photo_url)
  File "/usr/local/lib/python3.4/dist-packages/slackclient-0.14-py3.4.egg/slackclient/_client.py", line 22, in api_call
    return self.server.api_call(method, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/slackclient-0.14-py3.4.egg/slackclient/_server.py", line 102, in api_call
    reply = self.api_requester.do(self.token, method, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/slackclient-0.14-py3.4.egg/slackclient/_slackrequest.py", line 21, in do
    return urlopen(url, post_data.encode('utf-8'))
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: GATEWAY_TIMEOUT
Traceback (most recent call last):
  File "/home/cd334/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 471, in upload_image
    image_id = yield from self.bot._client.upload_image(image_response, filename=filename)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 472, in upload_image
    upload_url = (json.loads(res1.body.decode())['sessionStatus']
KeyError: 'sessionStatus'
Traceback (most recent call last):
  File "/home/cd334/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 471, in upload_image
    image_id = yield from self.bot._client.upload_image(image_response, filename=filename)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 472, in upload_image
    upload_url = (json.loads(res1.body.decode())['sessionStatus']
KeyError: 'sessionStatus'
Traceback (most recent call last):
  File "/home/cd334/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 471, in upload_image
    image_id = yield from self.bot._client.upload_image(image_response, filename=filename)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 472, in upload_image
    upload_url = (json.loads(res1.body.decode())['sessionStatus']
KeyError: 'sessionStatus'

After restart:
Traceback (most recent call last):
  File "/home/cd334/hangoutsbot/hangupsbot/plugins/slackrtm.py", line 471, in upload_image
    image_id = yield from self.bot._client.upload_image(image_response, filename=filename)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 472, in upload_image
    upload_url = (json.loads(res1.body.decode())['sessionStatus']
KeyError: 'sessionStatus'

Picture sync error:

Downloading https://slack-files.com/files-pub/something/screenshot_2015-11-11-10-17-39.png
11:35:52 INFO root: sending message to conversation Ugw1ps-5AW-C2fESzJp4AaABAQ
Uploading as screenshot_2015-11-11-10-17-39.png
slackrtm: Exception in upload_image: <class 'KeyError'>('sessionStatus')

What can be a problem? How we can repair it?

agent @cd334 (RES)

**Comment by nvrrvn** [comment]
https://github.com/tdryer/hangups/commit/fb499f8086a8b7aeb142660a9673959e3290b863

**Comment by cd334** [comment]
THX! Working, when I change the hangups.

**Comment by errror** [comment]
OK, error is fixed in hangups lib.
